server:
  port: 9090
  tomcat:
    uri-encoding: UTF-8  
  
spring:
  datasource:
    druid:  # druid连接池，mysql-8连接需要使用新的连接方式 com.mysql.cj.jdbc.Driver   characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
      url: jdbc:mysql://localhost:3306/springbootproject?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
  jpa:
    database: MYSQL
    show-sql: true      # 显示sql语句
    hibernate:
      ddl-auto: update # 正向工程
  devtools:
    restart:
      enabled: true    # 设置开启热部署
  freemarker:
    cache: false       # 页面不加载缓存，修改即时生效